### PR TITLE
release 2.7.0

### PR DESCRIPTION
**Pull request by showuon**
release 2.7.0

### CODE REVIEW

**Review by grdryn — COMMENTED** [review]
@showuon This looks better! :smiley_cat: I think the next step might be that PRs that are being released for the first time in this release should have the 2.7.0 milestone set on them (including ones that are still open but are intended to be in this release). I guess this would then populate the release notes like you can see for other releases at https://github.com/bf2fc6cc711aee1a0c2a/kas-broker-plugins/releases

**Comment by showuon** [comment]
Cool! Thank you, @grdryn ! But looks like the `github-action` is still not happy with the PR. Could I ignore it?

**Comment by grdryn** [comment]
@showuon Looking back on previous releases, it looks like this PR _should not_ have the milestone set on it (the milestone just needs to exist for it), and other PRs _should_ have the milestone set. I think this way, maybe the automation can recognise that the milestone is complete. I'll add the milestone to some other PRs and we should see that it has some sort of progress I think.

**Comment by grdryn** [comment]
@showuon I've added the milestone to what I believe are all of the PRs that this is the first release for, and I've removed it from this PR. You can see here now that it's considered 87% done: https://github.com/bf2fc6cc711aee1a0c2a/kas-broker-plugins/milestone/10

If we're _not_ going to wait for #54 for this release, then the milestone can be removed from that, and the milestone will then show as 100% done.

I'll dismiss that old review from the github-actions, and re-trigger it. I expect it will be green this time :)

**Comment by showuon** [comment]
Thanks for the info, Ger! Yes, we should wait for #54 for this release. I'll help review that PR tomorrow.

**Comment by grdryn** [comment]
> Thanks for the info, Ger!

No problem! If there's any of that stuff missing from the release docs, feel free to add!

**Comment by showuon** [comment]
@grdryn , all PRs in 2.7.0 milestone are done. I think we're good to merge it now.

**Review by grdryn — APPROVED** [review]
LGTM :+1:

**Pull request merged**
